name: CI/CD pipeline for node mysql projects

on:
    push:
        branches: [master]

jobs:

    deploy:
        runs-on: ubuntu-latest

        # run mysql in docker container
        services:

            mysql:
                image: mysql:8.0
                ports:
                    - 3307:3307
                env:
                    MYSQL_USER: admin
                    MYSQL_PASSWORD: admin123
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: UserDB
                    MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
                
                # options: >-
                #     --default-authentication-plugin=mysql_native_password
                #     --health-cmd="mysqladmin ping --silent"
                #     --health-interval=10s
                #     --health-timeout=5s
                #     --health-retries=3

        # Steps for running node & mysql
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: '18.x'
            
            - name: Install dependancy
              run: npm install

            - name: Mysql setup
              run: |
                until mysqladmin ping -h 127.0.0.1 -P 3307 --user=admin --password=admin123 --silent; do
                echo 'Waiting for MySQL...'
                sleep 3
                done
            
            - name: Create datbase & tables
              run: |
                mysql -h 127.0.0.1 -P 3307 -u admin -padmin123 -e "CREATE DATABASE IF NOT EXISTS UserDB;"
                mysql -h 127.0.0.1 -P 3307 -u admin -padmin123 UserDB < script.sql
            
            - name: Setup env varialbles
              env:
                PORT: 8080
                DB_HOST: 127.0.0.1
                DB_PORT: 3307
                DB_USER: admin
                DB_PASSWORD: admin123
                DB_DATABASE: UserDB
              run: echo "Env setup successfully.."
            
            - name: Start node server
              run: npm run prod